FROM node:lts-alpine
LABEL maintainer="Iohan, o mestre do kubernetes =)" description="api biodiesel nest"

ARG NESTJS_PORT
ARG TYPEORM_CONNECTION
ARG TYPEORM_HOST
ARG TYPEORM_PORT
ARG TYPEORM_USERNAME
ARG TYPEORM_PASSWORD
ARG TYPEORM_DATABASE
ARG TYPEORM_ENTITIES
ARG TYPEORM_SYNCHRONIZE
ARG TYPEORM_LOGGING
ARG AZURE_APP_INSIGHTS_KEY
ARG URL_PRODUCAO

ENV NESTJS_PORT ${NESTJS_PORT}
ENV TYPEORM_CONNECTION ${TYPEORM_CONNECTION}
ENV TYPEORM_HOST  ${TYPEORM_HOST}
ENV TYPEORM_PORT ${TYPEORM_PORT}
ENV TYPEORM_USERNAME ${TYPEORM_USERNAME}
ENV TYPEORM_PASSWORD ${TYPEORM_PASSWORD}
ENV TYPEORM_DATABASE ${TYPEORM_DATABASE}
ENV TYPEORM_ENTITIES ${TYPEORM_ENTITIES}
ENV TYPEORM_SYNCHRONIZE ${TYPEORM_SYNCHRONIZE}
ENV TYPEORM_LOGGING ${TYPEORM_LOGGING}
ENV AZURE_APP_INSIGHTS_KEY ${AZURE_APP_INSIGHTS_KEY}
ENV URL_PRODUCAO ${URL_PRODUCAO}

WORKDIR /usr/src/app
COPY package*.json ./
COPY $ENV ./
RUN echo $DB_USER ; \
    pwd ; \
    npm install  ; 
RUN apk add openjdk11 ;
RUN apk upgrade --update \
    && apk add -U tzdata \
    && cp /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime \
    && apk del tzdata \
    && rm -rf \
    /var/cache/apk/*


COPY . .

RUN npm run build;
CMD ["npm", "run", "start:prod"]
EXPOSE 4000
