-- MySQL Script generated by MySQL Workbench
-- Thu Dec 10 16:12:44 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema biodiesel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biodiesel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biodiesel` ;
USE `biodiesel` ;

-- -----------------------------------------------------
-- Table `biodiesel`.`versao_app`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biodiesel`.`versao_app` ;

CREATE TABLE IF NOT EXISTS `biodiesel`.`versao_app` (
  `id` INT UNSIGNED UNIQUE NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(90) NOT NULL,
  `descricao` TEXT NULL,
  `link_apk` TEXT NOT NULL,
  `data_lancamento` DATE NOT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `criado_em` TIMESTAMP NOT NULL DEFAULT NOW(),
  `atualizado_em` TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW(),
  `criado_por` INT UNSIGNED NULL,
  `atualizado_por` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE,
  INDEX `fk_versao_app_usuario_idx` (`criado_por` ASC) VISIBLE,
  INDEX `fk_versao_app_usuario2_idx` (`atualizado_por` ASC) VISIBLE,
  CONSTRAINT `fk_versao_app_usuario`
    FOREIGN KEY (`criado_por`)
    REFERENCES `biodiesel`.`usuario` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_versao_app_usuario2`
    FOREIGN KEY (`atualizado_por`)
    REFERENCES `biodiesel`.`usuario` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `biodiesel`.`dispositivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biodiesel`.`dispositivo` ;

CREATE TABLE IF NOT EXISTS `biodiesel`.`dispositivo` (
  `id` INT UNSIGNED UNIQUE NOT NULL AUTO_INCREMENT,
  `versao_app_id` INT UNSIGNED UNIQUE NOT NULL,
  `cliente_id` INT UNSIGNED NOT NULL,
  `usuario_id` INT UNSIGNED NOT NULL,
  `tipo` ENUM('PHONE', 'TABLET') NOT NULL,
  `modelo` VARCHAR(90) NOT NULL,
  `imei` VARCHAR(20) NOT NULL,
  `sistema` ENUM('ANDROID', 'IOS') NOT NULL,
  `versao_sistema` VARCHAR(20) NOT NULL,
  `versao_sdk` VARCHAR(20) NOT NULL,
  `resolucao` VARCHAR(20) NOT NULL,
  `escala_resolucao` VARCHAR(5) NOT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `data_ultima_atualizacao_app` TIMESTAMP NULL,
  `criado_em` TIMESTAMP NOT NULL DEFAULT NOW(),
  `atualizado_em` TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW(),
  PRIMARY KEY (`id`),
  INDEX `fk_dispositivo_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_dispositivo_cliente1_idx` (`cliente_id` ASC) VISIBLE,
  INDEX `fk_dispositivo_versao_app1_idx` (`versao_app_id` ASC) VISIBLE,
  UNIQUE INDEX `unique_dispositivo` (`imei` ASC, `usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_dispositivo_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `biodiesel`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_dispositivo_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `biodiesel`.`cliente` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_dispositivo_versao_app1`
    FOREIGN KEY (`versao_app_id`)
    REFERENCES `biodiesel`.`versao_app` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);


-- -----------------------------------------------------
-- Table `biodiesel`.`versao_app_instrucao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biodiesel`.`versao_app_instrucao` ;

CREATE TABLE IF NOT EXISTS `biodiesel`.`versao_app_instrucao` (
  `id` INT UNSIGNED UNIQUE NOT NULL AUTO_INCREMENT,
  `versao_app_id` INT UNSIGNED UNIQUE NOT NULL,
  `instrucao` TEXT NOT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `criado_em` TIMESTAMP NOT NULL DEFAULT NOW(),
  `atualizado_em` TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW(),
  `criado_por` INT UNSIGNED NULL,
  `atualizado_por` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_versao_app_instrucao_versao_app1_idx` (`versao_app_id` ASC) VISIBLE,
  INDEX `fk_versao_app_instrucao_usuario_idx` (`criado_por` ASC) VISIBLE,
  INDEX `fk_versao_app_instrucao_usuario2_idx` (`atualizado_por` ASC) VISIBLE,
  CONSTRAINT `fk_versao_app_instrucao_versao_app1`
    FOREIGN KEY (`versao_app_id`)
    REFERENCES `biodiesel`.`versao_app` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_versao_app_instrucao_usuario`
    FOREIGN KEY (`criado_por`)
    REFERENCES `biodiesel`.`usuario` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_versao_app_instrucao_usuario2`
    FOREIGN KEY (`atualizado_por`)
    REFERENCES `biodiesel`.`usuario` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `biodiesel`.`versao_app_instrucao_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biodiesel`.`versao_app_instrucao_usuario` ;

CREATE TABLE IF NOT EXISTS `biodiesel`.`versao_app_instrucao_usuario` (
  `versao_app_instrucao_id` INT UNSIGNED UNIQUE NOT NULL,
  `usuario_id` INT UNSIGNED NOT NULL,
  `executado_em` TIMESTAMP NULL,
  PRIMARY KEY (`versao_app_instrucao_id`, `usuario_id`),
  INDEX `fk_versao_app_instrucao_has_usuario_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_versao_app_instrucao_has_usuario_versao_app_instrucao1_idx` (`versao_app_instrucao_id` ASC) VISIBLE,
  UNIQUE INDEX `un_versao_app_instrucao_usuario` (`versao_app_instrucao_id` ASC, `usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_versao_app_instrucao_has_usuario_versao_app_instrucao1`
    FOREIGN KEY (`versao_app_instrucao_id`)
    REFERENCES `biodiesel`.`versao_app_instrucao` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_versao_app_instrucao_has_usuario_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `biodiesel`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
